# Generated by Django 4.2.20 on 2025-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('stuclass', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('student_contact', models.CharField(max_length=10, null=True)),
                ('parent_contact', models.CharField(max_length=10)),
                ('busroute', models.CharField(max_length=10)),
            ],
        ),
    ]
