# Generated by Django 4.2.20 on 2025-03-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_student_rollno_travelstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelstatus',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_status_by_rollno', to='backend.student', to_field='rollno'),
        ),
    ]
